-- Create the Quiz table
CREATE TABLE Quiz (
  Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  Name NVARCHAR(255) NOT NULL
);

-- Create the Question table
CREATE TABLE Question (
  Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  Text NVARCHAR(255) NOT NULL,
  QuizId INT NOT NULL FOREIGN KEY REFERENCES Quiz(Id) ON DELETE CASCADE
);

-- Create the Answer table
CREATE TABLE Answer (
  Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  Text NVARCHAR(255) NOT NULL,
  Points INT NOT NULL,
  QuestionId INT NOT NULL FOREIGN KEY REFERENCES Question(Id) ON DELETE CASCADE
);